[mypy]
# Плагин для Pydantic
plugins = pydantic.mypy

# Игнорирует отсутствующие импорты (например, SQLAlchemy internals)
ignore_missing_imports = True

# Не запрещает не типизированные функции
disallow_untyped_defs = False

# Проверяет функции без аннотаций, но без жестких ограничений
check_untyped_defs = False

# Не ругается на любые return Any
warn_return_any = False

# Позволяет Optional везде
no_implicit_optional = False

# Игнорирует ошибок для SQLAlchemy / SQLModel
[mypy-sqlalchemy.*]
ignore_errors = True

[mypy-sqlmodel.*]
ignore_errors = True

[mypy-app.models.*]
ignore_errors = True

[mypy-app.repositories.*]
ignore_errors = True
