"""add attribute webpush_notification in user, add webpush table

Revision ID: 0062fb7a1bbb
Revises: 544ecca3037b
Create Date: 2026-05-24 23:43:24.209322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0062fb7a1bbb'
down_revision: Union[str, Sequence[str], None] = '544ecca3037b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webpushsubscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('p256dh', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.add_column('user', sa.Column('webpush_notifications', sa.Boolean(), nullable=True))
    op.execute("UPDATE \"user\" SET webpush_notifications = true WHERE webpush_notifications IS NULL")
    op.alter_column('user', 'webpush_notifications', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'webpush_notifications')
    op.drop_table('webpushsubscription')
    # ### end Alembic commands ###
