"""create newtable

Revision ID: 24a605aade9f
Revises: 0062fb7a1bbb
Create Date: 2026-05-31 19:05:54.804372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '24a605aade9f'
down_revision: Union[str, Sequence[str], None] = '0062fb7a1bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirmemailtoken')
    op.drop_table('refreshtoken')
    op.drop_table('accesstoken')
    op.drop_table('webpushsubscription')
    op.drop_table('resetpasswordtoken')
    op.alter_column('subtasks', 'title',
               existing_type=sa.VARCHAR(length=150),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.add_column('user', sa.Column('pending_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_column('user', 'failed_login_attempts')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'locked_until')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('locked_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('failed_login_attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'pending_email')
    op.alter_column('subtasks', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.create_table('resetpasswordtoken',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='resetpasswordtoken_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='resetpasswordtoken_pkey')
    )
    op.create_table('webpushsubscription',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('p256dh', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('auth', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='webpushsubscription_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='webpushsubscription_pkey'),
    sa.UniqueConstraint('endpoint', name='webpushsubscription_endpoint_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('accesstoken',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='accesstoken_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='accesstoken_pkey')
    )
    op.create_table('refreshtoken',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='refreshtoken_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='refreshtoken_pkey')
    )
    op.create_table('confirmemailtoken',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='confirmemailtoken_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='confirmemailtoken_pkey')
    )
    # ### end Alembic commands ###
