"""add token version

Revision ID: 5506a16b796b
Revises: ffb2046a7d09
Create Date: 2026-06-14 23:09:18.077323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5506a16b796b'
down_revision: Union[str, Sequence[str], None] = 'ffb2046a7d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column('token_version', sa.Integer(), nullable=False, server_default='1'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token_version')
    # ### end Alembic commands ###
