"""add confirmed_at and unique s3_key in attachement

Revision ID: 60ad6a45eb9c
Revises: af4b577d8766
Create Date: 2026-05-04 10:42:53.112624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ad6a45eb9c'
down_revision: Union[str, Sequence[str], None] = 'af4b577d8766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', 
                  sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_attachments_s3_key'), table_name='attachments')
    op.create_index(op.f('ix_attachments_s3_key'), 'attachments', ['s3_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_s3_key'), table_name='attachments')
    op.create_index(op.f('ix_attachments_s3_key'), 'attachments', ['s3_key'], unique=False)
    op.drop_column('attachments', 'confirmed_at')
    # ### end Alembic commands ###
