"""change task position from int to float with data preservation

Revision ID: a137eec040e0
Revises: e8f70567fb6e
Create Date: 2026-04-07 13:18:35.144341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a137eec040e0'
down_revision: Union[str, Sequence[str], None] = 'e8f70567fb6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'position',
                    existing_type=sa.INTEGER(),
                    type_=sa.Float(),
                    existing_nullable=False,
                    postgresql_using='position::float')
    op.create_index(op.f('ix_tasks_position'), 'tasks', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_position'), table_name='tasks')
    op.alter_column('tasks', 'position',
                    existing_type=sa.Float(),
                    type_=sa.INTEGER(),
                    existing_nullable=False,
                    postgresql_using='position::integer')
    # ### end Alembic commands ###
