"""cascade delete fix

Revision ID: ba636b61495b
Revises: 649173f950bb
Create Date: 2026-05-18 11:41:13.591757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba636b61495b'
down_revision: Union[str, Sequence[str], None] = '649173f950bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_task_list_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'task_lists', ['task_list_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_task_list_id_fkey', 'tasks', 'task_lists', ['task_list_id'], ['id'])
    # ### end Alembic commands ###
