"""add column 'failed_login_attempts' in user model

Revision ID: e197d2cda40e
Revises: a137eec040e0
Create Date: 2026-04-19 12:20:03.618858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e197d2cda40e'
down_revision: Union[str, Sequence[str], None] = 'a137eec040e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user',
                  sa.Column(
                      'failed_login_attempts',
                      sa.Integer(),
                      nullable=False,
                      server_default='0'
                  )
                  )
    op.add_column('user', sa.Column('locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locked_until')
    op.drop_column('user', 'failed_login_attempts')
    # ### end Alembic commands ###
