"""update reminder

Revision ID: e5b4f67e681d
Revises: 03f3448dbe95
Create Date: 2026-06-08 15:19:02.768128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b4f67e681d'
down_revision: Union[str, Sequence[str], None] = '03f3448dbe95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_task_pending_reminder_time', 'reminders', ['task_id', 'reminder_at'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_task_pending_reminder_time', table_name='reminders', postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###
