"""add locked_login_until locked_vefiry_email_until locked_reset_password_until  fields to blocking_email table

Revision ID: e734b585b555
Revises: ea0e42723ebb
Create Date: 2026-06-01 11:26:51.301717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e734b585b555'
down_revision: Union[str, Sequence[str], None] = 'ea0e42723ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockingemail', sa.Column('locked_login_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('blockingemail', sa.Column('locked_verify_email_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('blockingemail', sa.Column('locked_reset_password_until', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('blockingemail', 'locked_until')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockingemail', sa.Column('locked_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('blockingemail', 'locked_reset_password_until')
    op.drop_column('blockingemail', 'locked_verify_email_until')
    op.drop_column('blockingemail', 'locked_login_until')
    # ### end Alembic commands ###
