"""update

Revision ID: eb3a5c2e3f83
Revises: 0062fb7a1bbb
Create Date: 2026-06-02 16:03:56.125902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb3a5c2e3f83'
down_revision: Union[str, Sequence[str], None] = '0062fb7a1bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attachments_uploaded_by_fkey'), 'attachments', type_='foreignkey')
    op.create_foreign_key(None, 'attachments', 'user', ['uploaded_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('reminders_task_id_fkey'), 'reminders', type_='foreignkey')
    op.create_foreign_key(None, 'reminders', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('subtasks', 'title',
               existing_type=sa.VARCHAR(length=150),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    op.drop_constraint(op.f('tags_user_id_fkey'), 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_foreign_key(op.f('tags_user_id_fkey'), 'tags', 'user', ['user_id'], ['id'])
    op.alter_column('subtasks', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.create_foreign_key(op.f('reminders_task_id_fkey'), 'reminders', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.create_foreign_key(op.f('attachments_uploaded_by_fkey'), 'attachments', 'user', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###
